#lang sicp
; processes generated by procedures -> recursive vs iterative

(define (fact n) ; linear recursive process
  (if (= n 1) 1
      (* n (fact (- n 1)))))

(define (fact1 n)
  (define (fact-iter prod ctr n) ; prod and ctr are state variables
    (if (> ctr n)
        prod
        (fact-iter (* ctr prod) (+ ctr 1) n)))
  (fact-iter 1 1 n))

(fact 5)
; this is a recursive process -> grows and then shrinks. time O(n), space O(n). "bureaucratic"
; (* 5 (fact 4))
; (* 5 (* 4 (fact 3)))
; (* 5 (* 4 (* 3 (fact 2))))
; (* 5 (* 4 (* 3 (* 2 (fact 1)))))
; (* 5 (* 4 (* 3 (* 2 1))))
; (* 5 (* 4 (* 3 2)))
; (* 5 (* 4 6))
; (* 5 24)
; 120
(fact1 5)
; this is an interative process - no grow, no shrink, can be resumed easily thanks to state variables. time O(n), space O(1)
; (fact-iter 1 1 5)
; (fact-iter 1 2 5)
; (fact-iter 2 3 5)
; (fact-iter 6 4 5)
; (fact-iter 24 5 5)
; (fact-iter 120 6 5)
; 120

(define (fib n) ; tree recursive process
  (cond ((= n 0) 0) 
        ((= n 1) 1) 
        (else (+ (fib (- n 1)) 
                 (fib (- n 2))))))
(fib 5)

; stack frames cause issue for iterative process created by a recursive program :(
; tail-call optimization to the rescue! why do we need a stack if, we don't need to do anything after fn returns? so stack is just cleaned :)

; below from slides:
; Iteration without looping constructs is expensive in space. 
; But we can avoid returning when the recursive call is the tail! 
; Saves stack space and makes iteration (nearly) as efficient as imperative languages with looping constructs.